// Code generated by protoc-gen-go. DO NOT EDIT.
// source: peer.proto

package bftmessages

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MsgType int32

const (
	MsgType_ClientRequest  MsgType = 0
	MsgType_ClientResponse MsgType = 1
	MsgType_PrePrepare     MsgType = 2
	MsgType_Prepare        MsgType = 3
	MsgType_Commit         MsgType = 4
	MsgType_Checkpoint     MsgType = 5
	MsgType_Probe          MsgType = 6
	MsgType_ProbeAck       MsgType = 7
	MsgType_NewConfig      MsgType = 8
	MsgType_SyncState      MsgType = 9
)

var MsgType_name = map[int32]string{
	0: "ClientRequest",
	1: "ClientResponse",
	2: "PrePrepare",
	3: "Prepare",
	4: "Commit",
	5: "Checkpoint",
	6: "Probe",
	7: "ProbeAck",
	8: "NewConfig",
	9: "SyncState",
}

var MsgType_value = map[string]int32{
	"ClientRequest":  0,
	"ClientResponse": 1,
	"PrePrepare":     2,
	"Prepare":        3,
	"Commit":         4,
	"Checkpoint":     5,
	"Probe":          6,
	"ProbeAck":       7,
	"NewConfig":      8,
	"SyncState":      9,
}

func (x MsgType) String() string {
	return proto.EnumName(MsgType_name, int32(x))
}

func (MsgType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_055ae5a865fc1c9e, []int{0}
}

type ReceivedChannel int32

const (
	ReceivedChannel_Client ReceivedChannel = 0
	ReceivedChannel_Peer   ReceivedChannel = 1
	ReceivedChannel_Coord  ReceivedChannel = 2
)

var ReceivedChannel_name = map[int32]string{
	0: "Client",
	1: "Peer",
	2: "Coord",
}

var ReceivedChannel_value = map[string]int32{
	"Client": 0,
	"Peer":   1,
	"Coord":  2,
}

func (x ReceivedChannel) String() string {
	return proto.EnumName(ReceivedChannel_name, int32(x))
}

func (ReceivedChannel) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_055ae5a865fc1c9e, []int{1}
}

type PeerMessage struct {
	FromNodeId           int32            `protobuf:"varint,1,opt,name=fromNodeId,proto3" json:"fromNodeId,omitempty"`
	MsgId                int32            `protobuf:"varint,2,opt,name=msgId,proto3" json:"msgId,omitempty"`
	EpochId              int32            `protobuf:"varint,3,opt,name=epochId,proto3" json:"epochId,omitempty"`
	Type                 MsgType          `protobuf:"varint,4,opt,name=type,proto3,enum=bftmessages.MsgType" json:"type,omitempty"`
	AttachedData         []byte           `protobuf:"bytes,5,opt,name=attachedData,proto3" json:"attachedData,omitempty"`
	Auth                 []*Authenticator `protobuf:"bytes,6,rep,name=auth,proto3" json:"auth,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *PeerMessage) Reset()         { *m = PeerMessage{} }
func (m *PeerMessage) String() string { return proto.CompactTextString(m) }
func (*PeerMessage) ProtoMessage()    {}
func (*PeerMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_055ae5a865fc1c9e, []int{0}
}

func (m *PeerMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerMessage.Unmarshal(m, b)
}
func (m *PeerMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerMessage.Marshal(b, m, deterministic)
}
func (m *PeerMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerMessage.Merge(m, src)
}
func (m *PeerMessage) XXX_Size() int {
	return xxx_messageInfo_PeerMessage.Size(m)
}
func (m *PeerMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerMessage.DiscardUnknown(m)
}

var xxx_messageInfo_PeerMessage proto.InternalMessageInfo

func (m *PeerMessage) GetFromNodeId() int32 {
	if m != nil {
		return m.FromNodeId
	}
	return 0
}

func (m *PeerMessage) GetMsgId() int32 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *PeerMessage) GetEpochId() int32 {
	if m != nil {
		return m.EpochId
	}
	return 0
}

func (m *PeerMessage) GetType() MsgType {
	if m != nil {
		return m.Type
	}
	return MsgType_ClientRequest
}

func (m *PeerMessage) GetAttachedData() []byte {
	if m != nil {
		return m.AttachedData
	}
	return nil
}

func (m *PeerMessage) GetAuth() []*Authenticator {
	if m != nil {
		return m.Auth
	}
	return nil
}

type CertificateMessage struct {
	Initialized          bool           `protobuf:"varint,1,opt,name=initialized,proto3" json:"initialized,omitempty"`
	CntPrepared          int32          `protobuf:"varint,2,opt,name=cntPrepared,proto3" json:"cntPrepared,omitempty"`
	Certificates         []*PeerMessage `protobuf:"bytes,3,rep,name=certificates,proto3" json:"certificates,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CertificateMessage) Reset()         { *m = CertificateMessage{} }
func (m *CertificateMessage) String() string { return proto.CompactTextString(m) }
func (*CertificateMessage) ProtoMessage()    {}
func (*CertificateMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_055ae5a865fc1c9e, []int{1}
}

func (m *CertificateMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CertificateMessage.Unmarshal(m, b)
}
func (m *CertificateMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CertificateMessage.Marshal(b, m, deterministic)
}
func (m *CertificateMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CertificateMessage.Merge(m, src)
}
func (m *CertificateMessage) XXX_Size() int {
	return xxx_messageInfo_CertificateMessage.Size(m)
}
func (m *CertificateMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_CertificateMessage.DiscardUnknown(m)
}

var xxx_messageInfo_CertificateMessage proto.InternalMessageInfo

func (m *CertificateMessage) GetInitialized() bool {
	if m != nil {
		return m.Initialized
	}
	return false
}

func (m *CertificateMessage) GetCntPrepared() int32 {
	if m != nil {
		return m.CntPrepared
	}
	return 0
}

func (m *CertificateMessage) GetCertificates() []*PeerMessage {
	if m != nil {
		return m.Certificates
	}
	return nil
}

type PayloadNewConfig struct {
	Members              []int32  `protobuf:"varint,1,rep,packed,name=members,proto3" json:"members,omitempty"`
	Leader               int32    `protobuf:"varint,2,opt,name=leader,proto3" json:"leader,omitempty"`
	DigestState          []byte   `protobuf:"bytes,3,opt,name=digestState,proto3" json:"digestState,omitempty"`
	DigestP              []byte   `protobuf:"bytes,4,opt,name=digestP,proto3" json:"digestP,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayloadNewConfig) Reset()         { *m = PayloadNewConfig{} }
func (m *PayloadNewConfig) String() string { return proto.CompactTextString(m) }
func (*PayloadNewConfig) ProtoMessage()    {}
func (*PayloadNewConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_055ae5a865fc1c9e, []int{2}
}

func (m *PayloadNewConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayloadNewConfig.Unmarshal(m, b)
}
func (m *PayloadNewConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayloadNewConfig.Marshal(b, m, deterministic)
}
func (m *PayloadNewConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayloadNewConfig.Merge(m, src)
}
func (m *PayloadNewConfig) XXX_Size() int {
	return xxx_messageInfo_PayloadNewConfig.Size(m)
}
func (m *PayloadNewConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_PayloadNewConfig.DiscardUnknown(m)
}

var xxx_messageInfo_PayloadNewConfig proto.InternalMessageInfo

func (m *PayloadNewConfig) GetMembers() []int32 {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *PayloadNewConfig) GetLeader() int32 {
	if m != nil {
		return m.Leader
	}
	return 0
}

func (m *PayloadNewConfig) GetDigestState() []byte {
	if m != nil {
		return m.DigestState
	}
	return nil
}

func (m *PayloadNewConfig) GetDigestP() []byte {
	if m != nil {
		return m.DigestP
	}
	return nil
}

type PayloadSyncState struct {
	Clients              []int32             `protobuf:"varint,1,rep,packed,name=clients,proto3" json:"clients,omitempty"`
	Certificate          *CertificateMessage `protobuf:"bytes,2,opt,name=certificate,proto3" json:"certificate,omitempty"`
	NewConfigMessage     *PeerMessage        `protobuf:"bytes,3,opt,name=newConfigMessage,proto3" json:"newConfigMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *PayloadSyncState) Reset()         { *m = PayloadSyncState{} }
func (m *PayloadSyncState) String() string { return proto.CompactTextString(m) }
func (*PayloadSyncState) ProtoMessage()    {}
func (*PayloadSyncState) Descriptor() ([]byte, []int) {
	return fileDescriptor_055ae5a865fc1c9e, []int{3}
}

func (m *PayloadSyncState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayloadSyncState.Unmarshal(m, b)
}
func (m *PayloadSyncState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayloadSyncState.Marshal(b, m, deterministic)
}
func (m *PayloadSyncState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayloadSyncState.Merge(m, src)
}
func (m *PayloadSyncState) XXX_Size() int {
	return xxx_messageInfo_PayloadSyncState.Size(m)
}
func (m *PayloadSyncState) XXX_DiscardUnknown() {
	xxx_messageInfo_PayloadSyncState.DiscardUnknown(m)
}

var xxx_messageInfo_PayloadSyncState proto.InternalMessageInfo

func (m *PayloadSyncState) GetClients() []int32 {
	if m != nil {
		return m.Clients
	}
	return nil
}

func (m *PayloadSyncState) GetCertificate() *CertificateMessage {
	if m != nil {
		return m.Certificate
	}
	return nil
}

func (m *PayloadSyncState) GetNewConfigMessage() *PeerMessage {
	if m != nil {
		return m.NewConfigMessage
	}
	return nil
}

type ConfigMessage struct {
	BasePort             int32    `protobuf:"varint,1,opt,name=basePort,proto3" json:"basePort,omitempty"`
	NodeCount            int32    `protobuf:"varint,2,opt,name=nodeCount,proto3" json:"nodeCount,omitempty"`
	Roles                []int32  `protobuf:"varint,3,rep,packed,name=roles,proto3" json:"roles,omitempty"`
	Addresses            []string `protobuf:"bytes,4,rep,name=addresses,proto3" json:"addresses,omitempty"`
	BasePorts            []int32  `protobuf:"varint,5,rep,packed,name=basePorts,proto3" json:"basePorts,omitempty"`
	OutgoingDoHash       bool     `protobuf:"varint,6,opt,name=outgoingDoHash,proto3" json:"outgoingDoHash,omitempty"`
	OutgoingDoSign       bool     `protobuf:"varint,7,opt,name=outgoingDoSign,proto3" json:"outgoingDoSign,omitempty"`
	IncomingDoHash       bool     `protobuf:"varint,8,opt,name=incomingDoHash,proto3" json:"incomingDoHash,omitempty"`
	IncomingVerifySign   bool     `protobuf:"varint,9,opt,name=incomingVerifySign,proto3" json:"incomingVerifySign,omitempty"`
	HashAlg              string   `protobuf:"bytes,10,opt,name=hashAlg,proto3" json:"hashAlg,omitempty"`
	SigType              SigType  `protobuf:"varint,11,opt,name=sigType,proto3,enum=bftmessages.SigType" json:"sigType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigMessage) Reset()         { *m = ConfigMessage{} }
func (m *ConfigMessage) String() string { return proto.CompactTextString(m) }
func (*ConfigMessage) ProtoMessage()    {}
func (*ConfigMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_055ae5a865fc1c9e, []int{4}
}

func (m *ConfigMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigMessage.Unmarshal(m, b)
}
func (m *ConfigMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigMessage.Marshal(b, m, deterministic)
}
func (m *ConfigMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigMessage.Merge(m, src)
}
func (m *ConfigMessage) XXX_Size() int {
	return xxx_messageInfo_ConfigMessage.Size(m)
}
func (m *ConfigMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigMessage proto.InternalMessageInfo

func (m *ConfigMessage) GetBasePort() int32 {
	if m != nil {
		return m.BasePort
	}
	return 0
}

func (m *ConfigMessage) GetNodeCount() int32 {
	if m != nil {
		return m.NodeCount
	}
	return 0
}

func (m *ConfigMessage) GetRoles() []int32 {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *ConfigMessage) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

func (m *ConfigMessage) GetBasePorts() []int32 {
	if m != nil {
		return m.BasePorts
	}
	return nil
}

func (m *ConfigMessage) GetOutgoingDoHash() bool {
	if m != nil {
		return m.OutgoingDoHash
	}
	return false
}

func (m *ConfigMessage) GetOutgoingDoSign() bool {
	if m != nil {
		return m.OutgoingDoSign
	}
	return false
}

func (m *ConfigMessage) GetIncomingDoHash() bool {
	if m != nil {
		return m.IncomingDoHash
	}
	return false
}

func (m *ConfigMessage) GetIncomingVerifySign() bool {
	if m != nil {
		return m.IncomingVerifySign
	}
	return false
}

func (m *ConfigMessage) GetHashAlg() string {
	if m != nil {
		return m.HashAlg
	}
	return ""
}

func (m *ConfigMessage) GetSigType() SigType {
	if m != nil {
		return m.SigType
	}
	return SigType_PKSig
}

type SendMessage struct {
	NodeId               []int32  `protobuf:"varint,1,rep,packed,name=nodeId,proto3" json:"nodeId,omitempty"`
	Message              []byte   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Hash                 []byte   `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	Signs                [][]byte `protobuf:"bytes,4,rep,name=signs,proto3" json:"signs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMessage) Reset()         { *m = SendMessage{} }
func (m *SendMessage) String() string { return proto.CompactTextString(m) }
func (*SendMessage) ProtoMessage()    {}
func (*SendMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_055ae5a865fc1c9e, []int{5}
}

func (m *SendMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessage.Unmarshal(m, b)
}
func (m *SendMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessage.Marshal(b, m, deterministic)
}
func (m *SendMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessage.Merge(m, src)
}
func (m *SendMessage) XXX_Size() int {
	return xxx_messageInfo_SendMessage.Size(m)
}
func (m *SendMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessage proto.InternalMessageInfo

func (m *SendMessage) GetNodeId() []int32 {
	if m != nil {
		return m.NodeId
	}
	return nil
}

func (m *SendMessage) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *SendMessage) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *SendMessage) GetSigns() [][]byte {
	if m != nil {
		return m.Signs
	}
	return nil
}

type ReceivedMessage struct {
	Channel              ReceivedChannel `protobuf:"varint,1,opt,name=channel,proto3,enum=bftmessages.ReceivedChannel" json:"channel,omitempty"`
	Message              []byte          `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ReceivedMessage) Reset()         { *m = ReceivedMessage{} }
func (m *ReceivedMessage) String() string { return proto.CompactTextString(m) }
func (*ReceivedMessage) ProtoMessage()    {}
func (*ReceivedMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_055ae5a865fc1c9e, []int{6}
}

func (m *ReceivedMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceivedMessage.Unmarshal(m, b)
}
func (m *ReceivedMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceivedMessage.Marshal(b, m, deterministic)
}
func (m *ReceivedMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceivedMessage.Merge(m, src)
}
func (m *ReceivedMessage) XXX_Size() int {
	return xxx_messageInfo_ReceivedMessage.Size(m)
}
func (m *ReceivedMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceivedMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ReceivedMessage proto.InternalMessageInfo

func (m *ReceivedMessage) GetChannel() ReceivedChannel {
	if m != nil {
		return m.Channel
	}
	return ReceivedChannel_Client
}

func (m *ReceivedMessage) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

func init() {
	proto.RegisterEnum("bftmessages.MsgType", MsgType_name, MsgType_value)
	proto.RegisterEnum("bftmessages.ReceivedChannel", ReceivedChannel_name, ReceivedChannel_value)
	proto.RegisterType((*PeerMessage)(nil), "bftmessages.PeerMessage")
	proto.RegisterType((*CertificateMessage)(nil), "bftmessages.CertificateMessage")
	proto.RegisterType((*PayloadNewConfig)(nil), "bftmessages.PayloadNewConfig")
	proto.RegisterType((*PayloadSyncState)(nil), "bftmessages.PayloadSyncState")
	proto.RegisterType((*ConfigMessage)(nil), "bftmessages.ConfigMessage")
	proto.RegisterType((*SendMessage)(nil), "bftmessages.SendMessage")
	proto.RegisterType((*ReceivedMessage)(nil), "bftmessages.ReceivedMessage")
}

func init() { proto.RegisterFile("peer.proto", fileDescriptor_055ae5a865fc1c9e) }

var fileDescriptor_055ae5a865fc1c9e = []byte{
	// 754 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x55, 0xcd, 0x8e, 0xeb, 0x34,
	0x14, 0xbe, 0xe9, 0x7f, 0x4f, 0xda, 0x12, 0xcc, 0xd5, 0x55, 0x34, 0xba, 0x82, 0x28, 0x0b, 0x54,
	0xdd, 0x45, 0x17, 0x45, 0x62, 0xc5, 0xa6, 0x64, 0x16, 0xcc, 0xe2, 0x8e, 0x2a, 0x17, 0xb1, 0x60,
	0xe7, 0x26, 0xa7, 0xa9, 0x35, 0x8d, 0x1d, 0x6c, 0x17, 0x54, 0x56, 0xbc, 0x00, 0x5b, 0xd6, 0xbc,
	0x04, 0x4f, 0xc3, 0xcb, 0x20, 0x3b, 0x49, 0x9b, 0xcc, 0x0c, 0x77, 0x97, 0xef, 0xf3, 0xe7, 0xe3,
	0xef, 0xfc, 0xd8, 0x01, 0x28, 0x11, 0xd5, 0xaa, 0x54, 0xd2, 0x48, 0xe2, 0xef, 0x0f, 0xa6, 0x40,
	0xad, 0x59, 0x8e, 0xfa, 0xee, 0x0b, 0x76, 0x36, 0x47, 0x14, 0x86, 0xa7, 0xcc, 0xc8, 0x5a, 0x11,
	0xff, 0xeb, 0x81, 0xbf, 0x45, 0x54, 0x1f, 0x2b, 0x15, 0xf9, 0x12, 0xe0, 0xa0, 0x64, 0xf1, 0x28,
	0x33, 0x7c, 0xc8, 0x42, 0x2f, 0xf2, 0x96, 0x43, 0xda, 0x62, 0xc8, 0x5b, 0x18, 0x16, 0x3a, 0x7f,
	0xc8, 0xc2, 0x9e, 0x5b, 0xaa, 0x00, 0x09, 0x61, 0x8c, 0xa5, 0x4c, 0x8f, 0x0f, 0x59, 0xd8, 0x77,
	0x7c, 0x03, 0xc9, 0x12, 0x06, 0xe6, 0x52, 0x62, 0x38, 0x88, 0xbc, 0xe5, 0x62, 0xfd, 0x76, 0xd5,
	0x32, 0xb4, 0xfa, 0xa8, 0xf3, 0x1f, 0x2f, 0x25, 0x52, 0xa7, 0x20, 0x31, 0xcc, 0x98, 0x31, 0x2c,
	0x3d, 0x62, 0x76, 0xcf, 0x0c, 0x0b, 0x87, 0x91, 0xb7, 0x9c, 0xd1, 0x0e, 0x47, 0x56, 0x30, 0xb0,
	0x49, 0x84, 0xa3, 0xa8, 0xbf, 0xf4, 0xd7, 0x77, 0x9d, 0x68, 0x9b, 0x76, 0x76, 0xd4, 0xe9, 0xe2,
	0xbf, 0x3c, 0x20, 0x09, 0x2a, 0xc3, 0x0f, 0x96, 0xc6, 0x26, 0xc9, 0x08, 0x7c, 0x2e, 0xb8, 0xe1,
	0xec, 0xc4, 0x7f, 0xc7, 0x2a, 0xcb, 0x09, 0x6d, 0x53, 0x56, 0x91, 0x0a, 0xb3, 0x55, 0x58, 0x32,
	0x85, 0x4d, 0xb2, 0x6d, 0x8a, 0x7c, 0x07, 0xb3, 0xf4, 0x16, 0x59, 0x87, 0x7d, 0x67, 0x29, 0xec,
	0x58, 0x6a, 0x15, 0x96, 0x76, 0xd4, 0xf1, 0x1f, 0x1e, 0x04, 0x5b, 0x76, 0x39, 0x49, 0x96, 0x3d,
	0xe2, 0x6f, 0x89, 0x14, 0x07, 0x9e, 0xdb, 0x2a, 0x16, 0x58, 0xec, 0x51, 0xe9, 0xd0, 0x8b, 0xfa,
	0xb6, 0x8a, 0x35, 0x24, 0xef, 0x60, 0x74, 0x42, 0x96, 0xa1, 0xaa, 0x9d, 0xd4, 0xc8, 0xda, 0xcc,
	0x78, 0x8e, 0xda, 0xec, 0x0c, 0x33, 0xe8, 0x6a, 0x3f, 0xa3, 0x6d, 0xca, 0xc6, 0xac, 0xe0, 0xd6,
	0xb5, 0x60, 0x46, 0x1b, 0x18, 0xff, 0x73, 0xb3, 0xb0, 0xbb, 0x88, 0xf4, 0x2a, 0x4f, 0x4f, 0x1c,
	0x85, 0xb9, 0x5a, 0xa8, 0x21, 0xd9, 0x80, 0xdf, 0xca, 0xc0, 0xf9, 0xf0, 0xd7, 0x5f, 0x75, 0xd2,
	0x7d, 0x59, 0x69, 0xda, 0xde, 0x43, 0xee, 0x21, 0x10, 0x4d, 0xb2, 0xb5, 0xc0, 0x59, 0xfe, 0x54,
	0xd9, 0x5e, 0xec, 0x88, 0xff, 0xec, 0xc3, 0xbc, 0xc3, 0x90, 0x3b, 0x98, 0xec, 0x99, 0xc6, 0xad,
	0x54, 0xa6, 0x9e, 0xd8, 0x2b, 0x26, 0xef, 0x61, 0x2a, 0x64, 0x86, 0x89, 0x3c, 0x0b, 0x53, 0x17,
	0xef, 0x46, 0xd8, 0x69, 0x56, 0xf2, 0x54, 0x77, 0x6f, 0x48, 0x2b, 0x60, 0xf7, 0xb0, 0x2c, 0x53,
	0xa8, 0x35, 0xea, 0x70, 0x10, 0xf5, 0x97, 0x53, 0x7a, 0x23, 0xec, 0x6a, 0x13, 0x5d, 0x87, 0x43,
	0xb7, 0xef, 0x46, 0x90, 0xaf, 0x61, 0x21, 0xcf, 0x26, 0x97, 0x5c, 0xe4, 0xf7, 0xf2, 0x07, 0xa6,
	0xed, 0xac, 0xda, 0xe9, 0x7a, 0xc6, 0x76, 0x75, 0x3b, 0x9e, 0x8b, 0x70, 0xfc, 0x5c, 0x67, 0x59,
	0xab, 0xe3, 0x22, 0x95, 0xc5, 0x2d, 0xde, 0xa4, 0xd2, 0x75, 0x59, 0xb2, 0x02, 0xd2, 0x30, 0x3f,
	0xa1, 0xe2, 0x87, 0x8b, 0x8b, 0x39, 0x75, 0xda, 0x57, 0x56, 0x6c, 0xa3, 0x8f, 0x4c, 0x1f, 0x37,
	0xa7, 0x3c, 0x84, 0xc8, 0x5b, 0x4e, 0x69, 0x03, 0xc9, 0x0a, 0xc6, 0x9a, 0xbb, 0x8b, 0x19, 0xfa,
	0xaf, 0x5c, 0xda, 0x5d, 0xb5, 0x46, 0x1b, 0x51, 0xcc, 0xc1, 0xdf, 0xa1, 0xc8, 0x9a, 0x66, 0xbc,
	0x83, 0x91, 0x68, 0x1e, 0x0f, 0x5b, 0x9b, 0x1a, 0x55, 0xc3, 0x5d, 0xf5, 0xbc, 0x57, 0x0d, 0x62,
	0x0d, 0x09, 0x81, 0x81, 0x3d, 0xbb, 0x9e, 0x5e, 0xf7, 0x6d, 0x1b, 0xa3, 0x79, 0x2e, 0xaa, 0xf2,
	0xcf, 0x68, 0x05, 0xe2, 0x14, 0x3e, 0xa3, 0x98, 0x22, 0xff, 0x15, 0xaf, 0xc7, 0x7d, 0x0b, 0xe3,
	0xf4, 0xc8, 0x84, 0xc0, 0x93, 0x6b, 0xfd, 0x62, 0xfd, 0xbe, 0xe3, 0xb6, 0x91, 0x27, 0x95, 0x86,
	0x36, 0xe2, 0xff, 0xb7, 0xf3, 0xe1, 0x6f, 0x0f, 0xc6, 0xf5, 0xcb, 0x44, 0x3e, 0x87, 0x79, 0xe2,
	0xe6, 0x9f, 0xe2, 0x2f, 0x67, 0xd4, 0x26, 0x78, 0x43, 0x08, 0x2c, 0x1a, 0x4a, 0x97, 0x52, 0x68,
	0x0c, 0x3c, 0xb2, 0x00, 0xd8, 0x2a, 0xac, 0x9f, 0x86, 0xa0, 0x47, 0x7c, 0x18, 0x37, 0xa0, 0x4f,
	0x00, 0x46, 0x89, 0x2c, 0x0a, 0x6e, 0x82, 0x81, 0x15, 0x26, 0x47, 0x4c, 0x9f, 0x4a, 0xc9, 0x85,
	0x09, 0x86, 0x64, 0x0a, 0xc3, 0xad, 0x92, 0x7b, 0x0c, 0x46, 0x64, 0x06, 0x13, 0xf7, 0xb9, 0x49,
	0x9f, 0x82, 0x31, 0x99, 0xc3, 0xf4, 0xfa, 0x2e, 0x04, 0x13, 0x0b, 0xaf, 0x77, 0x34, 0x98, 0x7e,
	0x58, 0xdf, 0xea, 0x50, 0x27, 0xe6, 0x4e, 0x71, 0xb6, 0x82, 0x37, 0x64, 0x02, 0x03, 0x7b, 0x85,
	0x02, 0xcf, 0xc6, 0x4f, 0xa4, 0x54, 0x59, 0xd0, 0xfb, 0x7e, 0xfe, 0x73, 0xfb, 0x67, 0xb0, 0x1f,
	0xb9, 0xe7, 0xff, 0x9b, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0xe9, 0x34, 0x75, 0x76, 0x2e, 0x06,
	0x00, 0x00,
}
